version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.6.10-alpine
    expose:
      - "5672"
    restart: unless-stopped

  worker:
    build: .
    command: celery -A tasks worker -B -s /tmp/celerybeat-schedule
    depends_on:
      - rabbitmq
    env_file:
      - .env
    environment:
      - RABBITMQ_URL=pyamqp://guest:guest@rabbitmq:5672//
    logging:
      driver: gcplogs
    restart: unless-stopped

  scheduler:
    build: .
    command: celery -A tasks beat -s /tmp/celerybeat-schedule --pidfile=/tmp/celerybeat.pid
    depends_on:
      - rabbitmq
    env_file:
      - .env
    environment:
      - RABBITMQ_URL=pyamqp://guest:guest@rabbitmq:5672//
    logging:
      driver: gcplogs
    restart: unless-stopped